name: CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Build
      shell: cmd
      run: |
        nuget restore
        msbuild sth1edwv.sln /p:Configuration=Release
        7z a program.zip bin\Release\*

    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: bin\Release\*

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "build${{github.run_attempt}}"
        prerelease: false
        title: "Automatic build of ${{github.sha}}"
        files: program.zip