name: CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      shell: cmd
      run: |
        cd editor
        dotnet publish sth1edwv.sln --configuration Release --output foo /p:Version=0.${{env.GITHUB_RUN_NUMBER}}+${{github.sha}} --runtime win-x64 -p:PublishSingleFile=true --no-self-contained
        7z a program.zip .\foo\*

    - name: Make artifact
      uses: actions/upload-artifact@v4
      with:
        name: program
        path: editor\foo\*

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v0.${{env.GITHUB_RUN_NUMBER}}"
        prerelease: false
        title: "Automatic build #${{env.GITHUB_RUN_NUMBER}}"
        files: editor/program.zip
