name: CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build Number Generator
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}  

    - name: Set version on AssemblyInfo.cs
      uses: dannevesdantas/set-version-assemblyinfo-win@v1.0.0
      with:
        version: "0.${{env.BUILD_NUMBER}}"
        
    - name: Build
      shell: cmd
      run: |
        cd editor
        dotnet publish sth1edwv.sln --configuration Release --output foo
        7z a program.zip .\foo\*

    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: editor\foo\*

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v0.${{env.BUILD_NUMBER}}"
        prerelease: false
        title: "Automatic build #${{env.BUILD_NUMBER}}"
        files: editor/program.zip