name: CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      shell: cmd
      run: |
        cd editor
        dotnet build sth1edwv.sln --configuration Release
        7z a program.zip bin\Release\net6.0-windows\*.exe bin\Release\net6.0-windows\*.dll

    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: editor\bin\Release\net6.0-windows\*

    - name: Build Number Generator
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}  

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v0.${{env.BUILD_NUMBER}}"
        prerelease: false
        title: "Automatic build #${{env.BUILD_NUMBER}}"
        files: editor/program.zip